FROM ubuntu:focal

RUN apt-get update && apt-get install -y git python3-pip docker.io && pip3 install awscli && apt-get clean -y

RUN apt-get clean -y

RUN mkdir -p /opt/bin

WORKDIR /opt/bin

RUN curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash

RUN ln -s /opt/bin/kustomize /usr/bin/

ENTRYPOINT [ "/bin/bash" ]
