FROM centos:7

RUN yum makecache && yum install -y git python3-pip docker && pip3 install awscli

RUN mkdir -p /opt/bin

WORKDIR /opt/bin

RUN curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash

RUN ln -s /opt/bin/kustomize /usr/bin/

ENTRYPOINT [ "/bin/bash" ]
