FROM ubuntu:focal

RUN apt-get update && apt-get install -y curl git python3-pip docker.io && pip3 install awscli && apt-get clean -y

RUN apt-get clean -y

RUN mkdir -p /opt/bin

WORKDIR /opt/bin

RUN curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash

RUN ln -s /opt/bin/kustomize /usr/bin/

RUN curl https://raw.githubusercontent.com/habitat-sh/habitat/master/components/hab/install.sh | bash

RUN hab license accept

RUN apt-get install -y jq

ENTRYPOINT [ "/bin/bash" ]
